/*
 * transform1.h
 *
 *  Created on: Nov 23, 2023
 *      Author: Arthur Sandor
 */


//this structure represents our Data Owner Secret Key Component
struct arsanvkabe_prv_do_s
{
	element_t d;   /* G_2 */
	 
	GArray* dummy_attr_array; /* bswabe_prv_comp_t's */ // the dummy attribute is first of all an attribute; the dummy attribute is managed by the data owner. Future works may assume multiple dummy attributes
};

//------------------------------------------------------

/*
 * first stage ciphertext from encryption by DO
 */
struct arsanvkabe_cph_DO_s
{
	element_t cs; /* G_T */
	element_t c;  /* G_1 */ 
	element_t g_s2;  /* G_1 */
	element_t c_attd; /* G_2 */
	char* p; /* anonymized access policy using set homomorphism hashing */
	element_t witness; /* sort of proof of ownership (like digital signature) */
};

//-------------------------------------------------------------------------------------------------------------------------------------------

/*
 * second stage ciphertext from encryption by RRD (Resource-Rich Device)
 */
struct arsanvkabe_cph_RRD_s
{
	element_t cs; /* G_T */
	element_t c;  /* G_1 */
	struct bswabe_policy_t* p; // anonymized access policy

	/* Existing parameters from DO ciphertext */
	element_t gs2_do;  /* G_1 */
	element_t cs_do; /* G_T */
	element_t c_do;  /* G_1 */
	element_t c_attd_do; /* G_2*/
	element_t witness; /* DO ciphertext issuance Proof */
};

//---------------------------------------------------------------------------------------------------------------------------------------------

/*
 *RRD key made of a GByteArray of AAKeys
 */
struct arsanvkabe_RRD_key_s
{
	GArray* AAkey_array;
};

//-------------------------------------------------------------------------------------------------------------------------------------------

/* 
 * This structure represents our user' secret key 
 */
struct arsanvkabe_prv_user_s
{
	arsanvkabe_prv_do_t* D;
	arsanvkabe_RRD_key_t* U; /* bswabe_prv_comp_t's */
};

//-----------------------------------------------------------------------------

/*
 * User public subkey DO_Out_key sent to RRD for policy evaluation and partial decryption
 */
struct arsanvkabe_user_rrd_subkey_s
{
	element_t dr;   /* G_2 */
	arsanvkabe_RRD_key_t* rrd_key; // struct arsanvkabe_RRD_key_s = GArray of bswabe_prv_comp_t

	/* Parameters related to the Dummy Attribute */
	element_t d_attd; /* G_2 */
	element_t t_attd  /* G_2 */
};

//----------------------------------------------
// testing
//----------------------------------------------
struct bswabe_msk_s
{
	element_t beta;    /* Z_r */
	element_t g_alpha; /* G_2 */ 
};
typedef struct bswabe_msk_s bswabe_msk_t;
//--------------------------------------------

/*
 * Data Owner Privilege Key Component in fahdabe
 */
typedef struct arsanvkabe_prv_do_s arsanvkabe_prv_do_t;


/*
 * second stage ciphertext generated by Resource-Rich Device (RRD) remote encryption in fahdabe
 */
typedef struct arsanvkabe_cph_RRD_s arsanvkabe_cph_RRD_t;

